using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdresWPF.Languages
{
    public class TranslationDesigner
    {
        /// <summary>
        ///   A strongly-typed resource class, for looking up localized strings, etc.
        /// </summary>
        // This class was auto-generated by the StronglyTypedResourceBuilder
        // class via a tool like ResGen or Visual Studio.
        // To add or remove a member, edit your .ResX file then rerun ResGen
        // with the /str option, or rebuild your VS project.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class Translations
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Translations()
            {
            }

            /// <summary>
            ///   Returns the cached ResourceManager instance used by this class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlantBeheer.WPF.Languages.Translations", typeof(Translations).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Overrides the current thread's CurrentUICulture property for all
            ///   resource lookups using this strongly typed resource class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Add.
            /// </summary>
            public static string Add
            {
                get
                {
                    return ResourceManager.GetString("Add", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Address.
            /// </summary>
            public static string Address
            {
                get
                {
                    return ResourceManager.GetString("Address", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Address: .
            /// </summary>
            public static string AddressTag
            {
                get
                {
                    return ResourceManager.GetString("AddressTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Close.
            /// </summary>
            public static string Close
            {
                get
                {
                    return ResourceManager.GetString("Close", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Confirm.
            /// </summary>
            public static string Confirm
            {
                get
                {
                    return ResourceManager.GetString("Confirm", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to adres.
            /// </summary>
            public static string adres
            {
                get
                {
                    return ResourceManager.GetString("adres", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Provide all data of gemeente!.
            /// </summary>
            public static string gemeente
            {
                get
                {
                    return ResourceManager.GetString("gemeente", resourceCulture);
                }
            }

            /// <summary>
            ///    Looks up a localized string similar to Name straat:.
            /// </summary>
            public static string straat
            {
                get
                {
                    return ResourceManager.GetString("straat", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Name adreslocatieId:.
            /// </summary>
            public static string adreslocatieId
            {
                get
                {
                    return ResourceManager.GetString("adreslocatieId", resourceCulture);
                }
            }
        

            /// <summary>
            ///   Looks up a localized string similar to Date.
            /// </summary>
            public static string Date
            {
                get
                {
                    return ResourceManager.GetString("Date", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Are you sure you want to delete this customer?.
            /// </summary>
            public static string DeleteCustomer
            {
                get
                {
                    return ResourceManager.GetString("DeleteCustomer", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Are you sure you want to delete this order?.
            /// </summary>
            public static string DeleteOrder
            {
                get
                {
                    return ResourceManager.GetString("DeleteOrder", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Are you sure you want to delete this product?.
            /// </summary>
            public static string DeleteProduct
            {
                get
                {
                    return ResourceManager.GetString("DeleteProduct", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Dutch.
            /// </summary>
            public static string Dutch
            {
                get
                {
                    return ResourceManager.GetString("Dutch", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to English.
            /// </summary>
            public static string English
            {
                get
                {
                    return ResourceManager.GetString("English", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to An unhandled exception just occurred: .
            /// </summary>
            public static string ExceptionMessage
            {
                get
                {
                    return ResourceManager.GetString("ExceptionMessage", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Exception Sample.
            /// </summary>
            public static string ExceptionSample
            {
                get
                {
                    return ResourceManager.GetString("ExceptionSample", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to No.
            /// </summary>
            public static string False
            {
                get
                {
                    return ResourceManager.GetString("False", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to File.
            /// </summary>
            public static string File
            {
                get
                {
                    return ResourceManager.GetString("File", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Languages.
            /// </summary>
            public static string Languages
            {
                get
                {
                    return ResourceManager.GetString("Languages", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Management.
            /// </summary>
            public static string Management
            {
                get
                {
                    return ResourceManager.GetString("Management", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Name.
            /// </summary>
            public static string Name
            {
                get
                {
                    return ResourceManager.GetString("Name", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Name: .
            /// </summary>
            public static string NameTag
            {
                get
                {
                    return ResourceManager.GetString("NameTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Number of products:.
            /// </summary>
            public static string NumberProductsTag
            {
                get
                {
                    return ResourceManager.GetString("NumberProductsTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Order.
            /// </summary>
            public static string Order
            {
                get
                {
                    return ResourceManager.GetString("Order", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Order number.
            /// </summary>
            public static string OrderID
            {
                get
                {
                    return ResourceManager.GetString("OrderID", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Orders.
            /// </summary>
            public static string Orders
            {
                get
                {
                    return ResourceManager.GetString("Orders", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Orders:.
            /// </summary>
            public static string OrdersTag
            {
                get
                {
                    return ResourceManager.GetString("OrdersTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Ordersystem.
            /// </summary>
            public static string Ordersystem
            {
                get
                {
                    return ResourceManager.GetString("Ordersystem", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Paid.
            /// </summary>
            public static string Paid
            {
                get
                {
                    return ResourceManager.GetString("Paid", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Paid:.
            /// </summary>
            public static string PaidTag
            {
                get
                {
                    return ResourceManager.GetString("PaidTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Price.
            /// </summary>
            public static string Price
            {
                get
                {
                    return ResourceManager.GetString("Price", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Price Paid.
            /// </summary>
            public static string PricePaid
            {
                get
                {
                    return ResourceManager.GetString("PricePaid", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Price:.
            /// </summary>
            public static string PriceTag
            {
                get
                {
                    return ResourceManager.GetString("PriceTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Provide all data of the product!.
            /// </summary>
            public static string ProductData
            {
                get
                {
                    return ResourceManager.GetString("ProductData", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Product already exists!.
            /// </summary>
            public static string ProductInList
            {
                get
                {
                    return ResourceManager.GetString("ProductInList", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Products.
            /// </summary>
            public static string Products
            {
                get
                {
                    return ResourceManager.GetString("Products", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Products:.
            /// </summary>
            public static string ProductsTag
            {
                get
                {
                    return ResourceManager.GetString("ProductsTag", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Remove.
            /// </summary>
            public static string Remove
            {
                get
                {
                    return ResourceManager.GetString("Remove", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Time.
            /// </summary>
            public static string Time
            {
                get
                {
                    return ResourceManager.GetString("Time", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Yes.
            /// </summary>
            public static string True
            {
                get
                {
                    return ResourceManager.GetString("True", resourceCulture);
                }
            }
        }
    }
}
